on:
  workflow_run:
    workflows: ['a']
    types: ['completed']
    branches: ['test/**']

env:
  PR_NUMBER: ${{ github.event.workflow_run.pull_requests[0].number }}
  BRANCH_NAME: 'renovate-snap/${{env.PR_NUMBER}}'
jobs:
  b:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo  ${{ env.BRANCH_NAME }}
